# Generated by Django 4.2.13 on 2024-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='descricao',
            field=models.TextField(default='F'),
        ),
    ]
