# Generated by Django 4.2.13 on 2024-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0003_atendimento_disponivel_alter_atendimento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
