# Generated by Django 4.2.13 on 2024-05-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0002_atendimento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
