# Generated by Django 4.2.13 on 2024-05-27 23:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PV', '0004_alter_atendimento_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doutor', models.CharField(choices=[('ENZO', 'Enzo'), ('FABIO', 'Fabio'), ('NG', 'Ng'), ('QUALQUER UM', 'Qualquer Um')], default='QUALQUER UM', max_length=100)),
                ('consulta', models.CharField(choices=[('CATARATA', 'Catarata'), ('CERATOCONE', 'Ceratocone'), ('CIRURGIA REFRATIVA', 'Cirurgia Refrativa'), ('CORNEA E CONJUNTIVA', 'Cornea e Conjuntiva'), ('GLAUCOMA', 'Glaucoma'), ('LENTES DE CONTATO', 'Lentes de Contato'), ('LENTES INTRAOCULAR PREMIUM', 'Lente Intraocular Premium'), ('OFTALMOLOGIA GERAL', 'Oftalmologia Geral'), ('OFTALMOPEDIATRIA', 'Oftalmopediatria'), ('PLASTICA OCULAR', 'Plastica Ocular')], default='', max_length=100)),
                ('data_consulta', models.DateTimeField(default=datetime.datetime.now)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
