# Generated by Django 4.2.13 on 2024-05-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0005_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='consulta',
            field=models.CharField(choices=[('CATARATA', 'Catarata'), ('CERATOCONE', 'Ceratocone'), ('CIRURGIA REFRATIVA', 'Cirurgia Refrativa'), ('CORNEA E CONJUNTIVA', 'Cornea e Conjuntiva'), ('GLAUCOMA', 'Glaucoma'), ('LENTES DE CONTATO', 'Lentes de Contato'), ('LENTES INTRAOCULAR PREMIUM', 'Lente Intraocular Premium'), ('OFTALMOLOGIA GERAL', 'Oftalmologia Geral'), ('OFTALMOPEDIATRIA', 'Oftalmopediatria'), ('PLASTICA OCULAR', 'Plastica Ocular')], max_length=100),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(),
        ),
    ]
