# Generated by Django 4.2.13 on 2024-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0006_alter_consulta_consulta_alter_consulta_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
