# Generated by Django 4.2.13 on 2024-05-29 19:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PV', '0009_alter_consulta_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulta',
            new_name='Consultas',
        ),
    ]
